# Generated by Django 5.0.4 on 2025-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
